version: "3"
services: 
    xray:
        image: teddysun/xray
        container_name: xray
        restart: always
      
        ports: 
            - 443:443
        volumes: 
            - ./xray/config:/etc/xray
            - ./xray/logs:/var/log/xray
            - ./cert:/home/root/cert
        networks: 
            - dockernet

   
    web:
        image: nginx:alpine
        container_name: nginx
        restart: always
        
        ports:
            - 80:80
        volumes: 
            - ./nginx/conf.d:/etc/nginx/conf.d
            - ./nginx/www:/var/www
            - ./nginx/nginx_logs:/var/log/nginx
            - ./nginx/web_logs:/etc/nginx/logs
            - ./cert:/etc/nginx/ssl
      
        networks: 
            - dockernet
